-- MySQL Script generated by MySQL Workbench
-- dom 07 jan 2024 20:26:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ESIdeal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ESIdeal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ESIdeal` ;
USE `ESIdeal` ;

-- -----------------------------------------------------
-- Table `ESIdeal`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ESIdeal`.`Administrador` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ESIdeal`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ESIdeal`.`Cliente` (
  `nif` VARCHAR(9) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `morada` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(12) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `notSMS` TINYINT NOT NULL,
  `notEmail` TINYINT NOT NULL,
  PRIMARY KEY (`nif`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ESIdeal`.`Competencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ESIdeal`.`Competencia` (
  `nrCompetencia` INT NOT NULL AUTO_INCREMENT,
  `nrCartao` INT NOT NULL,
  `tipo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`nrCompetencia`, `nrCartao`),
  CONSTRAINT `fk_CompetenciaFuncionario_Funcionario1`
    FOREIGN KEY (`nrCartao`)
    REFERENCES `ESIdeal`.`Funcionario` (`nrCartao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ESIdeal`.`Estacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ESIdeal`.`Estacao` (
  `idEstacao` INT NOT NULL AUTO_INCREMENT,
  `abertura` VARCHAR(5) NOT NULL,
  `fecho` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`idEstacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ESIdeal`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ESIdeal`.`Funcionario` (
  `nrCartao` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`nrCartao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ESIdeal`.`PostoTrabalho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ESIdeal`.`PostoTrabalho` (
  `nrPosto` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`nrPosto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ESIdeal`.`RegistoServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ESIdeal`.`RegistoServico` (
  `nrTurno` INT NOT NULL,
  `nrMarcacao` INT NOT NULL,
  `inicio` DATETIME NULL,
  `fim` DATETIME NULL,
  PRIMARY KEY (`nrTurno`, `nrMarcacao`),
  INDEX `fk_RegistoServico_RegistoTurno1_idx` (`nrTurno` ASC) VISIBLE,
  CONSTRAINT `fk_RegistoServico_ServicoAgendado1`
    FOREIGN KEY (`nrMarcacao`)
    REFERENCES `ESIdeal`.`ServicoAgendado` (`nrMarcacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RegistoServico_RegistoTurno1`
    FOREIGN KEY (`nrTurno`)
    REFERENCES `ESIdeal`.`RegistoTurno` (`nrTurno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ESIdeal`.`RegistoTurno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ESIdeal`.`RegistoTurno` (
  `nrTurno` INT NOT NULL AUTO_INCREMENT,
  `nrCartaoFuncionario` INT NOT NULL,
  `inicio` DATETIME NULL,
  `fim` DATETIME NULL,
  PRIMARY KEY (`nrTurno`, `nrCartaoFuncionario`),
  INDEX `fk_RegistoTurno_Funcionario1_idx` (`nrCartaoFuncionario` ASC) VISIBLE,
  CONSTRAINT `fk_RegistoTurno_Funcionario1`
    FOREIGN KEY (`nrCartaoFuncionario`)
    REFERENCES `ESIdeal`.`Funcionario` (`nrCartao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ESIdeal`.`Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ESIdeal`.`Servico` (
  `idServico` INT NOT NULL AUTO_INCREMENT,
  `designacao` VARCHAR(80) NOT NULL,
  `tempoNecessario` INT NOT NULL,
  `tipo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idServico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ESIdeal`.`ServicoAgendado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ESIdeal`.`ServicoAgendado` (
  `nrMarcacao` INT NOT NULL AUTO_INCREMENT,
  `idServico` INT NOT NULL,
  `matricula` VARCHAR(6) NOT NULL,
  `nrCartaoFuncionario` INT NOT NULL,
  `tipo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`nrMarcacao`, `idServico`, `matricula`, `nrCartaoFuncionario`),
  INDEX `fk_ServicoAgendado_Veiculo1_idx` (`matricula` ASC) VISIBLE,
  INDEX `fk_ServicoAgendado_Servico1_idx` (`idServico` ASC) VISIBLE,
  INDEX `fk_ServicoAgendado_Funcionario1_idx` (`nrCartaoFuncionario` ASC) VISIBLE,
  CONSTRAINT `fk_ServicoAgendado_Veiculo1`
    FOREIGN KEY (`matricula`)
    REFERENCES `ESIdeal`.`Veiculo` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ServicoAgendado_Servico1`
    FOREIGN KEY (`idServico`)
    REFERENCES `ESIdeal`.`Servico` (`idServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ServicoAgendado_Funcionario1`
    FOREIGN KEY (`nrCartaoFuncionario`)
    REFERENCES `ESIdeal`.`Funcionario` (`nrCartao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ESIdeal`.`ServicoAgendadoIncompleto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ESIdeal`.`ServicoAgendadoIncompleto` (
  `nrMarcacao` INT NOT NULL,
  `motivo` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`nrMarcacao`),
  CONSTRAINT `fk_ServicoAgendadoIncompleto_ServicoAgendado1`
    FOREIGN KEY (`nrMarcacao`)
    REFERENCES `ESIdeal`.`ServicoAgendado` (`nrMarcacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ESIdeal`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ESIdeal`.`Veiculo` (
  `matricula` VARCHAR(6) NOT NULL,
  `nifCliente` VARCHAR(9) NOT NULL,
  `tipo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`matricula`, `nifCliente`),
  INDEX `fk_Veiculo_Cliente_idx` (`nifCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Veiculo_Cliente`
    FOREIGN KEY (`nifCliente`)
    REFERENCES `ESIdeal`.`Cliente` (`nif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
